version: 0.2

phases:
  install:
    commands:
      - npm update -g npm
      - node -v
      - npm -v
      - yarn -v
  pre_build:
    commands:
      - cd frontend
      - echo Install dependencies
      - yarn install
      - echo NEXT_PUBLIC_API_ENDOPOINT=${NEXT_PUBLIC_API_ENDOPOINT} > .env.production
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      - echo Deploy started on `date`
      - aws s3 sync ./out/ s3://${DeployBucket} --acl public-read --cache-control public,max-age=604800
      - aws cloudfront create-invalidation --distribution-id ${Distribution} --paths "/*"
artifacts:
  files:
    - "out/**/*"
  base-directory: frontend
