version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: ./.devcontainer/frontend/Dockerfile
    container_name: todo-tree-frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/todo-tree
    command: /bin/bash -c "while sleep 1000; do :; done"
    stdin_open: true
