version: "3"

services:
  frontend:
    container_name: todo-tree-frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/todo-tree-frontend
    command: /bin/bash -c "while sleep 1000; do :; done"
    stdin_open: true

  backend:
    container_name: todo-tree-backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
      - "9080:9080"
    volumes:
      - ./backend:/todo-tree-backend
    command: /bin/bash -c "while sleep 1000; do :; done"
    stdin_open: true
  
  db:
    container_name: todo-tree-db
    build:
      context: .
      dockerfile: ./db/Dockerfile
    hostname: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: password
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    volumes:
      - "db-data:/var/lib/mysql"
      - "./db/my.conf:/etc/mysql/my.conf"
      - "./db/init/:/docker-entrypoint-initdb.d"

volumes:
  db-data:
    driver: local 