version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todo-tree-backend-api"
s3_bucket = "sam-todo-tree-backend-api"
s3_prefix = "todo-tree-backend-api"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
