version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todo-tree-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wuy6mzp7z1ij"
s3_prefix = "todo-tree-backend"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
